services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - C:\Users\user\Documents\Self_Practice\west-food-restaurant\backend\.env
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  frontend:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data:
